@echo off
REM Auto-generated by PowerLaunch portable distribution
cd /d "%~dp0"
"%cd%\runtime\bin\javaw.exe" -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dpowerlaunch.home="%cd%" -jar "%cd%\PowerLaunch.jar" %*
