#!/usr/bin/env bash
# Auto-generated by PowerLaunch portable distribution
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$DIR/runtime/bin/java" -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dpowerlaunch.home="$DIR" -jar "$DIR/PowerLaunch.jar" "$@"
